app:
   hostPort: 8081
   readTimeout: 60
   writeTimeout: 60


db:
  dialect: mysql
  dbName: ma_db
  host: 127.0.0.1
  user: root
  password: 123456
  port: 3306
  maxIdleConns: 5
  maxOpenConns: 20
  connMaxLifetime: 5

