definitions:
  ao.AddBillAo:
    properties:
      amount:
        type: number
      billDate:
        type: string
      description:
        type: string
      type:
        type: integer
    type: object
  ao.LoginAo:
    properties:
      nameName:
        type: string
      password:
        type: string
    type: object
  ao.RegisterAo:
    properties:
      confirmPassword:
        type: string
      nameName:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: login
      parameters:
      - description: ' '
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ao.LoginAo'
      produces:
      - application/json
      responses:
        "200":
          description: ok
      summary: 登录
      tags:
      - auth
  /bill:
    get:
      consumes:
      - application/json
      description: add bill
      parameters:
      - description: limit
        in: query
        name: limit
        required: true
        type: integer
      - description: offset
        in: query
        name: offset
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
      summary: 获取账单列表
      tags:
      - bill
    post:
      consumes:
      - application/json
      description: add bill
      parameters:
      - description: ' '
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ao.AddBillAo'
      produces:
      - application/json
      responses:
        "200":
          description: ok
      summary: 新增账单
      tags:
      - bill
  /user/register:
    post:
      consumes:
      - application/json
      description: register
      parameters:
      - description: ' '
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ao.RegisterAo'
      produces:
      - application/json
      responses:
        "200":
          description: ok
      summary: 注册
      tags:
      - user
swagger: "2.0"
